comments: comments.md
template_dir: templates

year: 2023

Vacances scolaires:
  css_class: "vacancesscolaires"
  dates:
    - 17/12/2022 - 02/01/2023
    - 18/02 - 05/03
    - 22/04 - 08/05
    - 08/07 - 03/09
    - 21/10 - 05/11
    - 23/12 - 07/01/2024

# Les jours fériés sont calculés automatiquement.