comments: comments.md
template_dir: templates

year: 2024

Vacances scolaires:
  css_class: "vacancesscolaires"
  dates:
    - 23/12/2023 - 07/01/2024
    - 10/02 - 25/02
    - 06/04 - 21/04
    - 06/07 - 01/09
    - 19/10 - 03/11
    - 21/12 - 05/01/2025

# Les jours fériés sont calculés automatiquement.
